//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "SystemSubTypeGroupProperty")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub group_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_property_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub system_property_id: String,
    pub order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::system_sub_type_group::Entity",
        from = "Column::GroupId",
        to = "super::system_sub_type_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SystemSubTypeGroup,
    #[sea_orm(
        belongs_to = "super::system_sub_type_property::Entity",
        from = "Column::SystemPropertyId",
        to = "super::system_sub_type_property::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SystemSubTypeProperty,
}

impl Related<super::system_sub_type_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemSubTypeGroup.def()
    }
}

impl Related<super::system_sub_type_property::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemSubTypeProperty.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
