//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "UserBacklinkIndex")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub source_id: String,
    #[sea_orm(column_type = "Text")]
    pub target_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub r#type: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub property_id: String,
    #[sea_orm(column_type = "Text")]
    pub property_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub property_value: Option<String>,
    pub ignore_divergence: i32,
    #[sea_orm(column_type = "Text")]
    pub last_synced_at: String,
    pub target_ignore: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub sub_property_id: Option<String>,
    pub is_system_property: i32,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_glossary_entry::Entity",
        from = "Column::TargetId",
        to = "super::user_glossary_entry::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserGlossaryEntry2,
    #[sea_orm(
        belongs_to = "super::user_glossary_entry::Entity",
        from = "Column::SourceId",
        to = "super::user_glossary_entry::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserGlossaryEntry1,
}

impl ActiveModelBehavior for ActiveModel {}
