//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "UserGlossaryNode")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub entry_type: String,
    #[sea_orm(column_type = "Text")]
    pub sub_type_id: String,
    #[sea_orm(column_type = "Text")]
    pub glossary_id: String,
    pub sort_index: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub integration_state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_glossary::Entity",
        from = "Column::GlossaryId",
        to = "super::user_glossary::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserGlossary,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::user_glossary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGlossary.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
