//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::devices::Entity")]
    Devices,
    #[sea_orm(has_many = "super::user_glossary::Entity")]
    UserGlossary,
    #[sea_orm(has_many = "super::user_glossary_entry::Entity")]
    UserGlossaryEntry,
    #[sea_orm(has_one = "super::user_settings::Entity")]
    UserSettings,
    #[sea_orm(has_many = "super::user_sub_type::Entity")]
    UserSubType,
    #[sea_orm(has_many = "super::user_sub_type_group::Entity")]
    UserSubTypeGroup,
    #[sea_orm(has_many = "super::user_sub_type_property::Entity")]
    UserSubTypeProperty,
    #[sea_orm(has_many = "super::user_tiers::Entity")]
    UserTiers,
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::user_glossary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGlossary.def()
    }
}

impl Related<super::user_glossary_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGlossaryEntry.def()
    }
}

impl Related<super::user_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSettings.def()
    }
}

impl Related<super::user_sub_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSubType.def()
    }
}

impl Related<super::user_sub_type_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSubTypeGroup.def()
    }
}

impl Related<super::user_sub_type_property::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSubTypeProperty.def()
    }
}

impl Related<super::user_tiers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTiers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
