//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "UserGlossary")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub genre: String,
    #[sea_orm(column_type = "Text")]
    pub sub_genre: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rt_description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text")]
    pub visibility: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub theme: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub integration_state: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::glossary_meta_data::Entity")]
    GlossaryMetaData,
    #[sea_orm(has_many = "super::user_glossary_node::Entity")]
    UserGlossaryNode,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::glossary_meta_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlossaryMetaData.def()
    }
}

impl Related<super::user_glossary_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGlossaryNode.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
