const LocationTypes: LocationType[] = [
  ['Ruin'],
  ['Temple'],
  ['Cave'],
  ['Dungeon'],
  ['Fortress'],
  ['Castle'],
  ['Tower'],
  ['Shrine'],
  ['Monument'],
  ['Mine'],
  ['Village'],
  ['Town'],
  ['City'],
  ['Capital'],
  ['Outpost'],
  ['Mountain'],
  ['Hill'],
  ['Glade'],
  ['Graveyard'],
  ['Store'],
  ['Market'],
  ['Library'],
  ['Academy'],
  ['Inn'],
  ['Tavern'],
  ['Farm'],
  ['Port'],
  ['Dock'],
  ['Ship'],
  ['Manor'],
  ['Barracks'],
  ['Watchtower'],
  ['Lighthouse'],
  ['Garden'],
  ['Arena'],
  ['Guildhall'],
  ['Workshop'],
  ['Palace'],
  ['Keep'],
  ['Sanctuary'],
  ['Camp'],
  ['Lumberyard'],
  ['Quarry'],
];

const ClimateTypeOptions: ClimateType[] = [
  ['tropical'],
  ['arid'],
  ['temperate'],
  ['polar'],
  ['subtropical'],
  ['continental'],
  ['icecap'],
];

const geographicEntryTypeOptions: GeographicEntryType[] = [
  ['forest'],
  ['mountain'],
  ['river'],
  ['lake'],
  ['ocean'],
  ['desert'],
  ['swamp'],
  ['cave'],
  ['hill'],
  ['plain'],
  ['valley'],
  ['glacier'],
  ['volcano'],
  ['canyon'],
  ['island'],
  ['archipelago'],
  ['peninsula'],
  ['bay'],
  ['gulf'],
  ['fjord'],
  ['steppe'],
  ['marsh'],
  ['wetland'],
  ['reef'],
  ['delta'],
  ['atoll'],
];

const TerrainTypeOptions: TerrainType[] = [
  ['forests'],
  ['mountains'],
  ['deserts'],
  ['swamps'],
  ['plains'],
  ['hills'],
  ['valleys'],
  ['plateaus'],
  ['tundra'],
  ['badlands'],
  ['coastal'],
  ['volcanic'],
  ['glacial'],
  ['taiga'],
];

const fallbackPropertyMap: Record<string, string[]> = {
  climates: ClimateTypeOptions,
  terrain: TerrainTypeOptions,
  nations: [],
  factions: [],
  locations: [],
  geographicType: geographicEntryTypeOptions,
  locationType: LocationTypes,
  regions: [],
  occupations: [],
  titles: [],
  traits: [],
  leaders: [],
  homeBases: [],
  allies: [],
  enemies: [],
  activeKeys: [],
  tags: [],
  sharedWith: [],
  resources: [],
  capitals: [],
  languages: [],
  persons: [],
  flags: [],
};

export default fallbackPropertyMap;
