const glossaryTypeMap = {
  region: {
    version: 1,
    description: '',
    tags: [],
    climate: '',
    terrain: '',
    factions: [],
    population: {},
    notableLocations: [],
    resources: [],
  },
  location: {
    version: 1,
    description: '',
    tags: [],
    type: '',
    region: [],
    climate: '',
    terrain: '',
    eventLog: [],
  },
  poi: {
    version: 1,
    description: '',
    tags: [],
    type: '',
    region: [],
    currentOccupants: [],
    nearbyFeatures: {},
  },
  person: {
    version: 1,
    description: '',
    tags: [],
    occupation: '',
    title: '',
    traits: [],
    faction: '',
    location: '',
    relationships: {},
    notoriety: '',
  },
  faction: {
    version: 1,
    description: '',
    tags: [],
    leader: '',
    homeBase: '',
    disposition: {},
    allies: [],
    enemies: [],
    influence: 0,
    notoriety: 0,
    cultureTags: [],
    activeKeys: [],
    passiveBonuses: {},
  },
  note: {
    version: 1,
    description: '',
  },
};

export default glossaryTypeMap;
