const glossaryTypeMap = {
  territory: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    climates: [],
    terrain: [],
    factions: [],
    population: {},
    locations: [],
    resources: [],
  },
  location: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    type: '',
    region: '',
    currentOccupants: [],
    nearbyFeatures: {},
    eventLog: [],
  },
  person: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    occupations: [],
    titles: [],
    traits: [],
    factions: [],
    locations: [],
    relationships: {},
    notoriety: '',
  },
  faction: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    leaders: [],
    homeBases: [],
    relationships: {},
    allies: [],
    enemies: [],
    influence: 0,
    notoriety: 0,
    cultureTags: [],
    activeKeys: [],
    passiveBonuses: {},
  },
  note: {
    version: 1,
    description: '',
    dataString: '',
    type: '',
    priority: 'low',
    dueDate: '',
    relatedEntries: {},
    tags: [],
    isArchived: false,
    isPinned: false,
    isShared: false,
    sharedWith: [],
    attachments: {},
  },
  continent: {
    version: 1,
    description: '',
    dataString: '',
    nations: [],
    regions: [],
    locations: [],
    resources: [],
    population: {},
    climates: [],
    terrain: [],
    eventLog: [],
  },
  domain: {
    version: 1,
    description: '',
    dataString: '',
    continent: [],
    regions: [],
    capital: [],
    population: {},
    economy: {},
    culture: {},
    languages: [],
    persons: [],
    eventLog: [],
    flags: [],
    history: [],
    relationships: {},
    locations: [],
    landmarks: [],
  },
  settlement: {
    version: 1,
    description: '',
    nation: '',
    region: '',
    persons: [],
    eventLog: [],
    locations: [],
    history: '',
    relationships: [],
  },
  event: {
    version: 1,
    description: '',
    dataString: '',
    significance: 'trivial',
    gameDate: '',
    frequency: 'annual',
    locations: [],
    relatedEntries: [],
    tags: [],
  },
  landmark: {
    version: 1,
    description: '',
    dataString: '',
    type: 'forest',
    regions: [],
    eventLog: [],
  },
  province: {
    version: 1,
    description: '',
    dataString: '',
    nation: '',
    terrain: [],
    locations: [],
    people: [],
    notableEvents: [],
    resources: [],
    population: {},
  },
};

export default glossaryTypeMap;
