//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "BacklinkIndex")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub source_id: String,
    #[sea_orm(column_type = "Text")]
    pub target_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub r#type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub property_id: String,
    #[sea_orm(column_type = "Text")]
    pub property_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub property_value: Option<String>,
    pub ignore_divergence: i32,
    #[sea_orm(column_type = "Text")]
    pub last_synced_at: String,
    pub target_ignore: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub sub_property_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::glossary_entry::Entity",
        from = "Column::TargetId",
        to = "super::glossary_entry::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GlossaryEntry2,
    #[sea_orm(
        belongs_to = "super::glossary_entry::Entity",
        from = "Column::SourceId",
        to = "super::glossary_entry::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GlossaryEntry1,
    #[sea_orm(
        belongs_to = "super::sub_type_property::Entity",
        from = "Column::PropertyId",
        to = "super::sub_type_property::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SubTypeProperty,
}

impl Related<super::sub_type_property::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubTypeProperty.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
