//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use sea_orm::EntityTrait;
use serde::{Deserialize, Serialize};

use crate::impl_parse_json;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "EntrySubType")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub content_type: String,
    #[sea_orm(column_type = "Text")]
    pub ref_id: String,
    pub version: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub forked_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub collaborators: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub editors: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<String>,
    pub is_immutable: i32,
    #[sea_orm(column_type = "Text")]
    pub entry_type: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub anchors: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub is_generic: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub context: Option<String>,
}

impl_parse_json!(Model, anchors);

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::glossary_entry::Entity")]
    GlossaryEntry,
    #[sea_orm(has_many = "super::sub_type_schema_group::Entity")]
    SubTypeSchemaGroup,
}

impl Related<super::glossary_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlossaryEntry.def()
    }
}

impl Related<super::sub_type_schema_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubTypeSchemaGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
