//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use crate::impl_parse_json;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Glossary")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub genre: String,
    #[sea_orm(column_type = "Text")]
    pub sub_genre: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    #[sea_orm(column_type = "Text")]
    pub content_type: String,
    #[sea_orm(column_type = "Text")]
    pub ref_id: String,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    pub is_immutable: i32,
    #[sea_orm(column_type = "Text")]
    pub visibility: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub collaborators: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub forked_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub editors: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub theme: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub integration_state: Option<String>,
}

impl_parse_json!(Model, integration_state, theme);

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::glossary_node::Entity")]
    GlossaryNode,
}

impl Related<super::glossary_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlossaryNode.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
