//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::impl_parse_json;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "GlossaryNode")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub entry_type: String,
    #[sea_orm(column_type = "Text")]
    pub file_type: String,
    #[sea_orm(column_type = "Text")]
    pub sub_type_id: String,
    #[sea_orm(column_type = "Text")]
    pub glossary_id: String,
    pub sort_index: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>, // eventually we will have custom icon support
    #[sea_orm(column_type = "Text", nullable)]
    pub integration_state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_id: Option<String>,
}

impl_parse_json!(Model, integration_state);

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::glossary::Entity",
        from = "Column::GlossaryId",
        to = "super::glossary::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Glossary,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::glossary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Glossary.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
