//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
//!
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "GlossaryEntry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub content_type: String,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    #[sea_orm(column_type = "Text")]
    pub format: String,
    #[sea_orm(column_type = "Text")]
    pub entry_type: String,
    #[sea_orm(column_type = "Text")]
    pub sub_type_id: String,
    #[sea_orm(column_type = "Text")]
    pub ref_id: String,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub forked_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub collaborators: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub editors: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<String>,
    pub is_immutable: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub groups: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub primary_anchor_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub primary_anchor_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub secondary_anchor_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub secondary_anchor_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tags: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub integration_state: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entry_sub_type::Entity",
        from = "Column::SubTypeId",
        to = "super::entry_sub_type::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    EntrySubType,
}

impl Related<super::entry_sub_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntrySubType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
