//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

// pub use super::backlink_index::Entity as BacklinkIndex;
// pub use super::entry_sub_type::Entity as EntrySubType;
// pub use super::glossary::Entity as Glossary;
// pub use super::glossary_entry::Entity as GlossaryEntry;
// pub use super::glossary_node::Entity as GlossaryNode;
// pub use super::sub_type_group::Entity as SubTypeGroup;
// pub use super::sub_type_group_property::Entity as SubTypeGroupProperty;
// pub use super::sub_type_property::Entity as SubTypeProperty;
// pub use super::sub_type_schema_group::Entity as SubTypeSchemaGroup;
