//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use crate::impl_parse_json;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "SubTypeProperty")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub ref_id: String,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub content_type: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub input_type: String,
    #[sea_orm(column_type = "Text")]
    pub shape: String,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub smart_sync: Option<String>,
    pub is_generic: i32,
}

impl_parse_json!(Model, smart_sync);

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backlink_index::Entity")]
    BacklinkIndex,
    #[sea_orm(has_many = "super::sub_type_group_property::Entity")]
    SubTypeGroupProperty,
}

impl Related<super::backlink_index::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacklinkIndex.def()
    }
}

impl Related<super::sub_type_group_property::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubTypeGroupProperty.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
