//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use crate::impl_parse_json;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "SubTypeGroup")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub ref_id: String,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub content_type: String,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub is_generic: i32,
}

impl_parse_json!(Model, display);

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sub_type_group_property::Entity")]
    SubTypeGroupProperty,
    #[sea_orm(has_many = "super::sub_type_schema_group::Entity")]
    SubTypeSchemaGroup,
}

impl Related<super::sub_type_group_property::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubTypeGroupProperty.def()
    }
}

impl Related<super::sub_type_schema_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubTypeSchemaGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
