//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "SubTypeSchemaGroup")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub schema_id: String,
    #[sea_orm(column_type = "Text")]
    pub group_id: String,
    pub order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entry_sub_type::Entity",
        from = "Column::SchemaId",
        to = "super::entry_sub_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EntrySubType,
    #[sea_orm(
        belongs_to = "super::sub_type_group::Entity",
        from = "Column::GroupId",
        to = "super::sub_type_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SubTypeGroup,
}

impl Related<super::entry_sub_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntrySubType.def()
    }
}

impl Related<super::sub_type_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubTypeGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {}
