//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "SystemSubTypeGroup")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rt_description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::system_sub_type_group_property::Entity")]
    SystemSubTypeGroupProperty,
    #[sea_orm(has_many = "super::system_sub_type_schema_group::Entity")]
    SystemSubTypeSchemaGroup,
}

impl Related<super::system_sub_type_group_property::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemSubTypeGroupProperty.def()
    }
}

impl Related<super::system_sub_type_schema_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemSubTypeSchemaGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
