//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "SystemSubType")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub entry_type: String,
    #[sea_orm(column_type = "Text")]
    pub anchors: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::system_glossary_entry::Entity")]
    SystemGlossaryEntry,
    #[sea_orm(has_many = "super::system_sub_type_schema_group::Entity")]
    SystemSubTypeSchemaGroup,
    #[sea_orm(has_many = "super::user_glossary_entry::Entity")]
    UserGlossaryEntry,
    #[sea_orm(has_many = "super::user_sub_type::Entity")]
    UserSubType,
}

impl Related<super::system_glossary_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemGlossaryEntry.def()
    }
}

impl Related<super::system_sub_type_schema_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemSubTypeSchemaGroup.def()
    }
}

impl Related<super::user_glossary_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGlossaryEntry.def()
    }
}

impl Related<super::user_sub_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSubType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
