//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "SystemGlossary")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub genre: String,
    #[sea_orm(column_type = "Text")]
    pub sub_genre: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rt_description: Option<String>,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub theme: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::system_glossary_node::Entity")]
    SystemGlossaryNode,
}

impl Related<super::system_glossary_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemGlossaryNode.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
