//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "SystemSubTypeSchemaGroup")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub subtype_id: String,
    #[sea_orm(column_type = "Text")]
    pub group_id: String,
    pub order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::system_sub_type::Entity",
        from = "Column::SubtypeId",
        to = "super::system_sub_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SystemSubType,
    #[sea_orm(
        belongs_to = "super::system_sub_type_group::Entity",
        from = "Column::GroupId",
        to = "super::system_sub_type_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SystemSubTypeGroup,
}

impl Related<super::system_sub_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemSubType.def()
    }
}

impl Related<super::system_sub_type_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemSubTypeGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
