//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "UserSubTypeGroupMetadata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub ref_id: String,
    pub version: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub published_at: Option<String>,
    pub download_count: i32,
    pub fork_count: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub forked_from: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub forked_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_sub_type_group::Entity",
        from = "Column::Id",
        to = "super::user_sub_type_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserSubTypeGroup,
}

impl Related<super::user_sub_type_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSubTypeGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
