//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "UserSubTypePropertyMetadata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub ref_id: String,
    pub version: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub forked_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub collaborators: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub editors: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_sub_type_property::Entity",
        from = "Column::Id",
        to = "super::user_sub_type_property::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserSubTypeProperty,
}

impl Related<super::user_sub_type_property::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSubTypeProperty.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
