//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "UserGlossaryEntry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub entry_type: String,
    #[sea_orm(column_type = "Text")]
    pub sub_type_id: String,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub groups: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub custom_properties: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub primary_anchor_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub primary_anchor_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub secondary_anchor_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub secondary_anchor_value: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub visibility: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::system_sub_type::Entity",
        from = "Column::SubTypeId",
        to = "super::system_sub_type::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SystemSubType,
    #[sea_orm(has_one = "super::user_glossary_entry_metadata::Entity")]
    UserGlossaryEntryMetadata,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::system_sub_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemSubType.def()
    }
}

impl Related<super::user_glossary_entry_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGlossaryEntryMetadata.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
