const glossaryTypeMap = {
  region: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    climates: [],
    terrain: [],
    nations: [],
    collectives: [],
    population: {},
    locations: [],
    landmarks: [],
    resources: [],
  },
  location: {
    version: 1,
    description: '',
    descDataString: '',
    locationType: [],
    tags: [],
    regions: [],
    occupants: [],
    nearbyFeatures: {},
    events: [],
  },
  person: {
    version: 1,
    description: '',
    descDataString: '',
    tags: [],
    occupations: [],
    titles: [],
    traits: [],
    collectives: [],
    locations: [],
    relationships: {},
    notoriety: '',
  },
  collective: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    leaders: [],
    homeBases: [],
    relationships: {},
    allies: [],
    enemies: [],
    influence: 0,
    notoriety: 0,
    cultureTags: [],
    activeKeys: [],
    passiveBonuses: {},
  },
  lore: {
    version: 1,
    description: '',
    descDataString: '',
    loreType: '',
    priority: 'low',
    dueDate: '',
    relatedEntries: {},
    tags: [],
    isArchived: false,
    isPinned: false,
    isShared: false,
    sharedWith: [],
    attachments: {},
  },
  continent: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    nations: [],
    regions: [],
    locations: [],
    resources: [],
    landmarks: [],
    population: {},
    climates: [],
    terrain: [],
    events: [],
  },
  nation: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    continents: [],
    regions: [],
    capitals: [],
    population: {},
    economy: {},
    cultures: {},
    languages: [],
    persons: [],
    events: [],
    flags: [],
    history: [],
    relationships: {},
    locations: [],
    landmarks: [],
  },
  settlement: {
    version: 1,
    description: '',
    tags: [],
    nations: [],
    regions: [],
    persons: [],
    events: [],
    locations: [],
    history: '',
    historyDataString: '',
    relationships: [],
  },
  event: {
    version: 1,
    description: '',
    descDataString: '',
    tags: [],
    significance: 'trivial',
    gameDate: '',
    frequency: 'annual',
    locations: [],
    relatedEntries: [],
  },
  landmark: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    geographicType: ['forest'],
    climates: [],
    terrain: [],
    locations: [],
    regions: [],
    events: [],
  },
  territory: {
    version: 1,
    description: '',
    dataString: '',
    tags: [],
    nations: [],
    terrain: [],
    locations: [],
    landmarks: [],
    persons: [],
    events: [],
    resources: [],
    population: {},
  },
};

export default glossaryTypeMap;
